gui:
  language: en
  showBranchCommitHash: true
  showPanelJumps: false
  showListFooter: false
  nerdFontsVersion: "3"
  skipRewordInEditorWarning: true
  skipStashWarning: true
  scrollHeight: 3
  theme:
    selectedLineBgColor:
      - "#b6e2ff"

git:
  commit:
    verbose: always
  paging:
    colorArg: always
    pager: delta --light --paging=never

os:
  edit: "hx {{filename}}"
  editAtLine: "hx {{filename}}"
  editAtLineAndWait: "hx {{filename}}"
  editInTerminal: true

promptToReturnFromSubprocess: false
