gui:
  language: en
  showBottomLine: false
  showIcons: true
  skipRewordInEditorWarning: true
  border: rounded

git:
  commit:
    verbose: always

os:
  edit: "hx {{filename}}"
  editAtLine: "hx {{filename}}"
  editAtLineAndWait: "hx {{filename}}"
  editInTerminal: true

promptToReturnFromSubprocess: false
