theme = "emacs"

[editor]
cursorline = false
auto-save = true
rulers = [80]
color-modes = true

[editor.statusline]
left = [
  "mode",
  "spinner",
  "file-name",
  "diagnostics",
]
center = []
right = [
  "position",
  "position-percentage",
  "spacer",
  "selections",
  "file-encoding",
  "file-line-ending",
  "file-type",
]

[editor.statusline.mode]
normal = "NORMAL"
insert = "INSERT"
select = "SELECT"

[editor.cursor-shape]
normal = "block"
insert = "underline"
select = "block"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "all"
nbsp = "all"
tab = "all"
newline = "none"

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1
