edition = "2021"
unstable_features = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
max_width = 80
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
