# General
ignore-menu-bar: false
new-windows-to-main: false
follow-space-thrown-windows: true

window-minimum-width: 0
window-minimum-height: 0
window-margins: true
window-margin-size: 1
smart-window-margins: true

screen-padding-left: 0
screen-padding-top: 0
screen-padding-right: 0
screen-padding-bottom: 0

enables-layout-hud: true
enables-layout-hud-on-space-change: false

# Layouts
restore-layouts-on-launch: true
window-resize-step: 4
layouts:
  - tall
  - wide
  - fullscreen
  - floating

# Shortcuts
mod1:
  - control
  - command
  - option

mod2:
  - control
  - command
  - option
  - shift

focus-cw:
  mod: mod1
  key: j
focus-ccw:
  mod: mod1
  key: k
focus-main:
  mod: mod1
  key: m

swap-cw:
  mod: mod2
  key: j
swap-ccw:
  mod: mod2
  key: k
swap-main:
  mod: mod1
  key: enter

focus-screen-1:
  mod: mod1
  key: ","
focus-screen-2:
  mod: mod1
  key: "."
focus-screen-3:
  mod: mod1
  key: k

throw-screen-1:
  mod: mod2
  key: ","
throw-screen-2:
  mod: mod2
  key: "."
throw-screen-3:
  mod: mod2
  key: p

throw-space-1:
  mod: mod2
  key: a
throw-space-2:
  mod: mod2
  key: o
throw-space-3:
  mod: mod2
  key: e
throw-space-4:
  mod: mod2
  key: i
throw-space-5:
  mod: mod2
  key: u

expand-main:
  mod: mod1
  key: l
shrink-main:
  mod: mod1
  key: h

increase-main:
  mod: mod1
  key: "["
decrease-main:
  mod: mod1
  key: "]"
cycle-layout:
  mod: mod2
  key: "]"
cycle-layout-backward:
  mod: mod2
  key: "["

select-floating-layout:
  mod: mod1
  key: 1
select-wide-layout:
  mod: mod1
  key: 2
select-tall-layout:
  mod: mod1
  key: 3
select-fullscreen-layout:
  mod: mod1
  key: 4

relaunch-amethyst:
  mod: mod1
  key: ";"

# Mouse
mouse-follows-focus: false
focus-follows-mouse: false
mouse-swaps-windows: false

# Floating
float-small-windows: true
floating-is-blacklist: true
floating:
  - com.apple.iBooksX

# Debug
debug-layout-info: false
use-canary-build: true
