theme = "bold-intellij-light"

[editor]
true-color = true
undercurl = true
auto-save = true
rulers = [80]
color-modes = true
default-line-ending = "lf"

[editor.lsp]
display-inlay-hints = true

[editor.statusline]
left = [
  "mode",
  "spinner",
  "file-name",
  "file-modification-indicator",
  "spacer",
  "version-control",
  "spacer",
  "spacer",
  "spacer",
  "selections",
  "primary-selection-length",
  "diagnostics",
]
center = []
right = [
  "position",
  "position-percentage",
  "spacer",
  "file-encoding",
  "file-line-ending",
  "file-type",
]

[editor.statusline.mode]
normal = "NORMAL"
insert = "INSERT"
select = "SELECT"

[editor.cursor-shape]
insert = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "all"
nbsp = "all"
tab = "all"
newline = "none"

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[keys.normal]
F9 = ["dap_launch", "dap_continue"]
S-F9 = "dap_pause"
A-F9 = "dap_restart"
A-F2 = "dap_terminate"
F7 = "dap_step_in"
F8 = "dap_next"
A-F8 = "dap_step_out"
F2 = "dap_toggle_breakpoint"
S-F2 = "dap_edit_condition"
