theme = "bold-intellij-light"

[editor]
true-color = true
undercurl = true
cursorline = false
auto-save = true
rulers = [80]
color-modes = true
preview-completion-insert = true
completion-replace = false
default-line-ending = "lf"
insert-final-newline = true

[editor.smart-tab]
supersede-menu = true

[editor.lsp]
display-inlay-hints = true
goto-reference-include-declaration = false

[editor.statusline]
left = [
  "mode",
  "spinner",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",
  "spacer",
  "version-control",
  "spacer",
  "spacer",
  "spacer",
  "selections",
  "primary-selection-length",
  "diagnostics",
]
center = []
right = [
  "register",
  "position",
  "position-percentage",
  "spacer",
  "file-encoding",
  "file-line-ending",
  "file-type",
]

[editor.statusline.mode]
normal = "NORMAL"
insert = "INSERT"
select = "SELECT"

[editor.cursor-shape]
normal = "block"
insert = "underline"
select = "block"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "all"
nbsp = "all"
tab = "all"
newline = "none"

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1
